formatter: markdown table  # this is required

version: ">= 0.14"

header-from: ./.terraform-docs/HEADER.md
footer-from: ./.terraform-docs/FOOTER.md

sections:
  hide: []
  show: []

content: |-

  {{ .Header }}

  {{ .Inputs }}
  
  {{ .Outputs }}
  
  {{ .Providers }}
  
  {{ .Requirements }}
  
  {{ .Modules }}
  
  {{ .Resources }}

  {{ include "./.terraform-docs/DETAILS.md"}}
  
  {{ .Footer }}

output:
  file: README.md
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->    

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true